name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test sumar
      id: test-sumar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test sumar
        setup-command: ''
        command: mvn test -Dgroups=sumar
        timeout: 10
        max-score: 1
    - name: Test restar
      id: test-restar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test restar
        setup-command: ''
        command: mvn test -Dgroups=restar
        timeout: 10
        max-score: 1
    - name: Test multiplicar
      id: test-multiplicar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test multiplicar
        setup-command: ''
        command: mvn test -Dgroups=multiplicar
        timeout: 10
        max-score: 1
    - name: Test dividir
      id: test-dividir
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test dividir
        setup-command: ''
        command: mvn test -Dgroups=dividir
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-SUMAR_RESULTS: "${{steps.test-sumar.outputs.result}}"
        TEST-RESTAR_RESULTS: "${{steps.test-restar.outputs.result}}"
        TEST-MULTIPLICAR_RESULTS: "${{steps.test-multiplicar.outputs.result}}"
        TEST-DIVIDIR_RESULTS: "${{steps.test-dividir.outputs.result}}"
      with:
        runners: test-sumar,test-restar,test-multiplicar,test-dividir
